# Generated by Django 3.2.13 on 2022-06-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220612_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='patente',
        ),
    ]
